"""max string good for

Revision ID: 102f6d00d3ce
Revises: 1a64079142c4
Create Date: 2025-03-17 00:20:21.337185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '102f6d00d3ce'
down_revision: Union[str, None] = '1a64079142c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'ingredients',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('products', 'image_url',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=1500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image_url',
               existing_type=sa.String(length=1500),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('products', 'ingredients',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
