"""max string good for

Revision ID: 893ec36ce2d3
Revises: 102f6d00d3ce
Create Date: 2025-03-17 00:20:55.759144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '893ec36ce2d3'
down_revision: Union[str, None] = '102f6d00d3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'ingredients',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'ingredients',
               existing_type=sa.String(length=3000),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###
